import localFont from "next/font/local";
import "./globals.css";
import { Navigation } from "../components/navBars/NavBar";
import { AuthProvider, useAuth } from "../providers/context";
import { NextUIProvider } from "@nextui-org/react";
import {ThemeProvider as NextThemesProvider} from "next-themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Volunteer Connect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <AuthProvider>
              <NextUIProvider>
                <NextThemesProvider attribute="class" defaultTheme="dark">
                  <Navigation/>
                    {children}
                </NextThemesProvider>
              </NextUIProvider>
            </AuthProvider>
      </body>
    </html>
  );
}
